/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:53383ac2-25e5-446e-b2c2-feb3e334f7b8",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "58dc90d8374646c7a7d69c64c6ca81d1",
    "aws_mobile_analytics_app_region": "us-east-1"
};




export default awsmobile;
